- 1.1.11
- _NAME: MX Keys Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, speed-change, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, reprogrammable-keys, persistent-remappable-keys, crown-smooth,
    divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 0x1000
  _modelId: B35B408A0000
  _sensitive: {backlight: false, divert-keys: true, fn-swap: true, multiplatform: true}
  _serial: 2737FC7E
  _unitId: 2737FC7E
  _wpid: 408A
  change-host: null
  disable-keyboard-keys: {0x1: false, 0x2: false, 0x4: false, 0x8: false, 0x10: false}
  divert-keys: {0xa: 0x1, 0x6e: 0x0, 0x6f: 0x1, 0xbf: 0x0, 0xc7: 0x0, 0xc8: 0x0, 0xd1: 0x0, 0xd2: 0x0, 0xd3: 0x0, 0xe0: 0x1, 0xe1: 0x1, 0xe2: 0x0, 0xe3: 0x0,
    0xe4: 0x0, 0xe5: 0x0, 0xe6: 0x0, 0xe7: 0x0, 0xe8: 0x0, 0xe9: 0x0, 0xea: 0x0, 0xeb: 0x0, 0xec: 0x0}
  fn-swap: false
  multiplatform: 0x0
- _NAME: MX Master 3 Wireless Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, speed-change, backlight, backlight_level,
    backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer, adc_power_management]
  _battery: 0x1000
  _dpi-sliding: 0x10
  _modelId: B02340820000
  _sensitive: {change-host: false, divert-keys: true, hires-scroll-mode: true, hires-smooth-invert: true, hires-smooth-resolution: true, reprogrammable-keys: true,
    scroll-ratchet: false, thumb-scroll-invert: true, thumb-scroll-mode: false}
  _serial: 4D753DD2
  _unitId: 4D753DD2
  _wpid: '4082'
  change-host: null
  divert-keys: {0x52: 0x3, 0x53: 0x0, 0x56: 0x0, 0xc3: 0x2, 0xc4: 0x2}
  dpi: 1050
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {0x50: 0x50, 0x51: 0x51, 0x52: 0x52, 0x53: 0x53, 0x56: 0x56, 0xc3: 0xc3, 0xc4: 0xc3}
  scroll-ratchet: 0x2
  smart-shift: 0xa
  thumb-scroll-invert: false
  thumb-scroll-mode: true
- _NAME: MX Anywhere 2
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 5E3E0082
  _wpid: '4072'
